CREATE DATABASE IF NOT EXISTS penzugyek
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_hungarian_ci;

USE penzugyek;

CREATE TABLE IF NOT EXISTS Bevetel (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Forras VARCHAR(100) NOT NULL,
  Osszeg DECIMAL(12,2) NOT NULL,
  Datum DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Kiadas (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Kategoria VARCHAR(100) NOT NULL,
  Leiras VARCHAR(255),
  Osszeg DECIMAL(12,2) NOT NULL,
  Datum DATE NOT NULL
);